media:
  - name: images
    label: Images
    input: assets/images
    output: /assets/images
    extensions: [jpg, jpeg, png, gif, webp, svg]

content:
  - name: actualites
    label: Actualités
    type: collection
    path: content/actualites
    format: yaml-frontmatter
    filename: "{year}-{month}-{day}-{slug}.md"
    view:
      layout: list
      primary: title
      fields: [title, date, author, type, published]
      sort: [date, title]
      default:
        sort: date
        order: desc
    fields:
      - name: title
        label: Titre
        type: string
        required: true
      - name: date
        label: Date de publication
        type: date
        required: true
      - name: author
        label: Auteur
        type: string
        required: true
      - name: excerpt
        label: Résumé
        type: text
        required: true
      - name: type
        label: Type de publication
        type: string
        widget: select
        options:
          - Article
          - Rapport
          - Étude
          - Publication
          - Analyse
          - Recherche
        default: Article
        required: true
      - name: published
        label: Publié
        type: boolean
        default: true
      - name: body
        label: Contenu
        type: rich-text
        required: true
