media:
  - name: images
    label: Images
    input: assets/images
    output: /assets/images
    extensions:
      - jpg
      - jpeg
      - png
      - gif
      - webp
      - svg

content:
  - name: actualites
    label: Actualités
    type: collection
    path: content/actualites
    filename: "{year}-{month}-{day}-{slug}.md"
    format: yaml-frontmatter
    view:
      layout: list
      primary: title
      fields:
        - title
        - date
        - author
        - published
      sort:
        - date
      default:
        sort: date
        order: desc
    fields:
      - name: title
        label: Titre
        type: string
        required: true
      - name: date
        label: Date de publication
        type: date
        required: true
      - name: author
        label: Auteur
        type: string
        required: true
      - name: excerpt
        label: Résumé
        type: text
        required: true
      - name: body
        label: Contenu
        type: rich-text
        required: true
      - name: published
        label: Publié
        type: boolean
        default: true