content:
  - name: actualites
    label: Actualités
    type: collection
    path: content/actualites
    format: yaml-frontmatter
    fields:
      - name: title
        label: Titre
        type: string
        required: true
      - name: date
        label: Date de publication
        type: date
        required: true
      - name: author
        label: Auteur
        type: string
        required: true
      - name: excerpt
        label: Résumé
        type: text
        required: true
      - name: body
        label: Contenu
        type: rich-text
        required: true
      - name: published
        label: Publié
        type: boolean
        default: true