backend:
  name: github
  repo: Frd100/wpc-site
  branch: main
  base_url: https://api.netlify.com
  auth_endpoint: auth

media_folder: "images/actualites"
public_folder: "/images/actualites"

collections:
  - name: "actualites"
    label: "Actualités"
    folder: "content/actualites"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Titre", name: "title", widget: "string"}
      - {label: "Date de publication", name: "date", widget: "datetime"}
      - {label: "Auteur", name: "author", widget: "string"}
      - {label: "Résumé", name: "excerpt", widget: "text"}
      - {label: "Contenu", name: "body", widget: "markdown"}
      - {label: "Publié", name: "published", widget: "boolean", default: true}
